CLEANUP_BASE_ACTION_SPACE_SIZE = 9
HARVEST_BASE_ACTION_SPACE_SIZE = 8
SWITCH_BASE_ACTION_SPACE_SIZE = 8

REWARD_UPPER_BOUND = 60

EPSILON_CONSTANT = 1

HARVEST_PERIODIC_PERT_FREQUENCY = 1.8e6
TAXIS_PERIODIC_PERT_FREQUENCY = 2.3e6
# HARVEST_SINGLE_PERT_FREQUENCY = 500 * 10**3

CLEANUP_PERIODIC_PERT_FREQUENCY = 10e6
# CLEANUP_SINGLE_PERT_FREQUENCY = 5 * 10**6

MAX_PERTURBATION_MAGNITUDE = 200.0
MAX_PERCENT_OF_WALLS_ALLOWED = 0.2

