name: causal

dependencies:
    - python==3.6.7
    - pip:
        - numpy==1.16.0
        - gym==0.10.9
        - matplotlib==3.1.3
        - opencv-python
        - ray==0.7.6
        - tensorflow==2.0.0
        - setproctitle
        - psutil
        - lz4
        - boto3==1.4.8
        - redis==3.3.2
        - pytz

